read_hdl -vhdl {color_ctrl.vhd}
read_hdl -vhdl {display_ctrl.vhd}
read_hdl -vhdl {module_test.vhd}
read_hdl -vhdl {player_fsm.vhd}
read_hdl -vhdl {spi_v3.vhd}
read_hdl -vhdl {stable_map.vhd}
read_hdl -vhdl {texture_ctrl.vhd}
read_hdl -vhdl {tile_ctrl.vhd}
read_hdl -vhdl {vga.vhd}
read_hdl -vhdl {color_ctrl-behaviour.vhd}
read_hdl -vhdl {display_ctrl-behaviour.vhd}
read_hdl -vhdl {module_test-behaviour.vhd}
read_hdl -vhdl {player_fsm-behaviour.vhd}
read_hdl -vhdl {spi_v3-behaviour.vhd}
read_hdl -vhdl {stable_map-behaviour.vhd}
read_hdl -vhdl {texture_ctrl-behaviour.vhd}
read_hdl -vhdl {tile_ctrl-behaviour.vhd}
read_hdl -vhdl {vga-behaviour.vhd}
read_hdl -vhdl {display_ctrl_behavioural_cfg.vhd}
read_hdl -vhdl {color_ctrl_behavioural_cfg.vhd}
read_hdl -vhdl {tile_ctrl_behavioural_cfg.vhd}
read_hdl -vhdl {texture_ctrl_behaviour_cfg.vhd}
read_hdl -vhdl {stable_map_behaviour_cfg.vhd}
read_hdl -vhdl {spi_v3_behaviour_cfg.vhd}
read_hdl -vhdl {vga_behaviour_cfg.vhd}
read_hdl -vhdl {player_fsm_behaviour_cfg.vhd}
read_hdl -vhdl {module_test_behaviour_cfg.vhd}
